name: rtx

permissions:
  contents: write

on:
  workflow_dispatch:  # manual runs while we debug

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TZ: Australia/Sydney
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Show working dir
        run: |
          pwd
          ls -la
          echo "---- tree rt ----"
          ls -la rt || true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run generator (with PYTHONPATH=rt)
        env:
          PYTHONPATH: rt
        run: |
          set -euxo pipefail
          python rt/runner.py

      - name: List outputs
        run: |
          echo "---- repo root ----"
          ls -la
          echo "---- artifacts ----"
          ls -la artifacts || true
          if test -f artifacts/idx.json; then
            echo "---- idx.json head ----"
            head -n 40 artifacts/idx.json
          else
            echo "idx.json NOT FOUND"
          fi

      - name: Upload artifacts from job (for inspection)
        uses: actions/upload-artifact@v4
        with:
          name: job-artifacts
          path: artifacts/*
          if-no-files-found: warn

      - name: Prepare git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Show git status before commit
        run: |
          git status
          echo "---- changed files ----"
          git ls-files -m -o --exclude-standard || true

      - name: Commit outputs
        run: |
          set -euxo pipefail
          git add artifacts/*.csv artifacts/idx.json 2>/dev/null || true
          git commit -m "refresh $(date -Iseconds)" || echo "No changes"
          git push
