name: rtx
on:
  schedule:
    - cron: '0 * * * 1'  # every hour on Monday
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TZ: Australia/Sydney
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install requests beautifulsoup4
      - name: Gate to exactly 17:00 local on Mondays
        run: |
          DOW=$(date +'%u')
          HOUR=$(date +'%H')
          if [ "$DOW" != "1" ] || [ "$HOUR" != "17" ]; then
            echo "Not Monday 17:00 Australia/Sydney; exiting."
            exit 0
          fi
      - run: python -m pip install --upgrade pip
      - run: python rt/runner.py
      - name: Commit outputs
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add artifacts/*.csv artifacts/idx.json || true
          git commit -m "refresh $(date -Iseconds)" || echo "No changes"
          git push
