name: rtx

# ✅ Allow this workflow to push back to the repo
permissions:
  contents: write

on:
  # You can still run it manually
  workflow_dispatch:
  schedule:
    - cron: '0 * * * 1'   # hourly Mondays

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TZ: Australia/Sydney
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # keep token for pushing

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run generator
        # PYTHONPATH ensures imports like "from ingest import ..." work when running rt/runner.py
        env:
          PYTHONPATH: rt
        run: |
          python rt/runner.py

      - name: Show outputs (for debugging)
        run: |
          echo "==== repo tree ===="
          ls -la
          echo "==== artifacts ===="
          ls -la artifacts || true
          echo "==== idx.json preview ===="
          (test -f artifacts/idx.json && head -n 30 artifacts/idx.json) || echo "no idx.json"

      - name: Prepare git (avoid safe.directory error)
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Commit outputs
        run: |
          git add artifacts/*.csv artifacts/idx.json 2>/dev/null || true
          git commit -m "refresh $(date -Iseconds)" || echo "No changes"
          git push
